# -*- coding: utf-8 -*-
"""Task 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12PFNSVhIm7UhS4DSyhtmsf1UHta7y51B
"""

!pip install pyspark

!pip install imdby

!pip install cinemagoer

import imdb

ia = imdb.IMDb()
top250 = ia.get_top250_movies()
for movie_count in range(0, 10):
    
    movie = ia.get_movie(top250[movie_count].movieID)
    
    print(movie['title'])
    print(*movie['genres'], sep=", ")
    import pyspark.sql.types as t

